// Barrel entry for the @molecule-ai/contracts npm package.
//
// This file is the package shim — hand-written and NOT generated. It only
// re-exports the generated bindings under gen/ts/ (which ARE generated by
// tools/gen-ts.mjs and must never be hand-edited; the codegen-drift gate
// enforces that). Keeping the shim outside gen/ leaves generator output
// byte-identical so the drift gate stays green.
//
// Consumers:
//   import { RequiredTool, RegisterRequest } from "@molecule-ai/contracts";
// or the per-domain subpaths:
//   import { RequiredTool } from "@molecule-ai/contracts/contract";
//   import { RegisterRequest } from "@molecule-ai/contracts/workspace-comms";

export * from "./gen/ts/contract_gen";
export * from "./gen/ts/workspace_comms_gen";
