#!/usr/bin/env node
// gen-ts.mjs — generate TypeScript bindings from the MCP plugin-delivery contract IDL.
//
// IMPORTANT (the whole point of this generator):
//   Every emitted constant VALUE is DERIVED from the contract JSON instance at
//   `mcp/mcp-plugin-delivery.contract.json`. NOTHING is hardcoded here — there is
//   deliberately no string literal "provision_workspace" (or any other contract
//   value) anywhere in this file. Rename the verb in the contract and re-run, and
//   the generated `RequiredTool` changes with it. That is what makes the schema
//   `const` pin + the validate CI + the drift gate load-bearing end to end.
//
// Usage:
//   node tools/gen-ts.mjs            # write gen/ts/contract_gen.ts
//   node tools/gen-ts.mjs --check    # print to stdout, do not write (debug)
//
// Run from the repo root (paths below are resolved relative to this file's
// location, so cwd does not matter).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const CONTRACT_PATH = resolve(repoRoot, "mcp/mcp-plugin-delivery.contract.json");
const OUT_PATH = resolve(repoRoot, "gen/ts/contract_gen.ts");

// --- read the canonical IDL instance ----------------------------------------
const raw = readFileSync(CONTRACT_PATH, "utf8");
let contract;
try {
  contract = JSON.parse(raw);
} catch (err) {
  console.error(`gen-ts: ${CONTRACT_PATH} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// --- derive the scalar string constants we expose ----------------------------
// Each entry maps a TypeScript const identifier to the contract field it is
// DERIVED from. This is the SAME scalar set the Go generator emits (gen-go.mjs);
// keep the two in lockstep. The nested `runtimes` / `port` objects are
// intentionally NOT modeled here in this first pass (see tools/README.md
// "Follow-ons").
const SCALAR_CONSTS = [
  // TS const name           contract field             doc
  ["RequiredTool", "required_tool",
    "the singular tool verb the concierge management MCP must expose; the degrade gate fails closed if it is absent on the live surface (the #3082 phantom-verb invariant)."],
  ["MCPServerName", "mcp_server_name",
    "logical name of the management-mode MCP server descriptor."],
  ["SettingsKey", "key",
    "top-level key inside the settings file under which MCP servers are declared."],
  ["DefaultSettingsPath", "settings_path",
    "default (claude_code) settings file path the rendered MCP descriptor is written to."],
  ["LoadedMCPToolsField", "loaded_mcp_tools_field",
    "name of the field reporting the set of tools actually loaded from the MCP server."],
  ["RuntimePresentField", "runtime_present_field",
    "name of the runtime-reported boolean field indicating the MCP server is present."],
  ["LegacyBinaryPath", "legacy_binary_path",
    "filesystem path of the legacy MCP server binary older presence probes checked."],
];

const derived = [];
for (const [tsName, field, doc] of SCALAR_CONSTS) {
  const value = contract[field];
  if (typeof value !== "string") {
    console.error(
      `gen-ts: contract field '${field}' is missing or not a string (got ${JSON.stringify(value)}); ` +
      `cannot derive TS const ${tsName}. The contract instance must validate against the schema first.`
    );
    process.exit(1);
  }
  derived.push({ tsName, field, doc, value });
}

// --- escape a derived value for safe embedding in a TS string literal --------
function tsStringLiteral(s) {
  return JSON.stringify(s); // TypeScript and JSON share double-quoted escape semantics for these values.
}

// --- emit -------------------------------------------------------------------
const lines = [];
lines.push("// Code generated by tools/gen-ts.mjs — DO NOT EDIT.");
lines.push("//");
lines.push("// Source of truth: mcp/mcp-plugin-delivery.contract.json (validated against");
lines.push("// mcp/mcp-plugin-delivery.schema.json). Every value below is DERIVED from that");
lines.push("// contract instance, never hand-written. Regenerate with:");
lines.push("//");
lines.push("//     node tools/gen-ts.mjs");
lines.push("//");
lines.push("// A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
lines.push("// fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
lines.push("");
lines.push("// Derived scalar string constants from the MCP plugin-delivery contract.");
lines.push("// `as const` pins each to its string-literal type, mirroring the Go consts.");
for (const { tsName, field, doc, value } of derived) {
  lines.push(`// ${tsName} is derived from contract field "${field}": ${doc}`);
  lines.push(`export const ${tsName} = ${tsStringLiteral(value)} as const;`);
  lines.push("");
}
// drop the trailing blank line before EOF
if (lines[lines.length - 1] === "") lines.pop();
lines.push("");

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-ts: wrote ${OUT_PATH} (${derived.length} consts derived from ${CONTRACT_PATH})`);
