#!/usr/bin/env node
// gen-python.mjs — generate Python bindings from the MCP plugin-delivery contract IDL.
//
// Why Node (.mjs) and not Python? For consistency and zero added toolchain: all
// three generators (Go, TS, Python) are Node scripts, so the drift gate needs
// only `node` — no Python interpreter in CI. Generating Python *source* from
// Node is fine; the emitted module is plain idiomatic Python.
//
// IMPORTANT (the whole point of this generator):
//   Every emitted constant VALUE is DERIVED from the contract JSON instance at
//   `mcp/mcp-plugin-delivery.contract.json`. NOTHING is hardcoded here — there is
//   deliberately no string literal "provision_workspace" (or any other contract
//   value) anywhere in this file. Rename the verb in the contract and re-run, and
//   the generated `REQUIRED_TOOL` changes with it. That is what makes the schema
//   `const` pin + the validate CI + the drift gate load-bearing end to end.
//
// Usage:
//   node tools/gen-python.mjs            # write gen/python/contract_gen.py
//   node tools/gen-python.mjs --check    # print to stdout, do not write (debug)
//
// Run from the repo root (paths below are resolved relative to this file's
// location, so cwd does not matter).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const CONTRACT_PATH = resolve(repoRoot, "mcp/mcp-plugin-delivery.contract.json");
const OUT_PATH = resolve(repoRoot, "gen/python/contract_gen.py");

// --- read the canonical IDL instance ----------------------------------------
const raw = readFileSync(CONTRACT_PATH, "utf8");
let contract;
try {
  contract = JSON.parse(raw);
} catch (err) {
  console.error(`gen-python: ${CONTRACT_PATH} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// --- derive the scalar string constants we expose ----------------------------
// Each entry maps a logical const identifier to the contract field it is DERIVED
// from. This is the SAME scalar set the Go and TS generators emit; keep the
// three in lockstep. Python idiom = module-level UPPER_SNAKE_CASE constants, so
// we carry the canonical PascalCase identifier and convert it deterministically
// below. The nested `runtimes` / `port` objects are intentionally NOT modeled
// here in this first pass (see tools/README.md "Follow-ons").
const SCALAR_CONSTS = [
  // Canonical name          contract field             doc
  ["RequiredTool", "required_tool",
    "the singular tool verb the concierge management MCP must expose; the degrade gate fails closed if it is absent on the live surface (the #3082 phantom-verb invariant)."],
  ["MCPServerName", "mcp_server_name",
    "logical name of the management-mode MCP server descriptor."],
  ["SettingsKey", "key",
    "top-level key inside the settings file under which MCP servers are declared."],
  ["DefaultSettingsPath", "settings_path",
    "default (claude_code) settings file path the rendered MCP descriptor is written to."],
  ["LoadedMCPToolsField", "loaded_mcp_tools_field",
    "name of the field reporting the set of tools actually loaded from the MCP server."],
  ["RuntimePresentField", "runtime_present_field",
    "name of the runtime-reported boolean field indicating the MCP server is present."],
  ["LegacyBinaryPath", "legacy_binary_path",
    "filesystem path of the legacy MCP server binary older presence probes checked."],
];

// PascalCase -> UPPER_SNAKE_CASE (idiomatic Python module constant), with runs
// of capitals (e.g. "MCP") kept together: MCPServerName -> MCP_SERVER_NAME.
function toUpperSnake(pascal) {
  return pascal
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

const derived = [];
for (const [name, field, doc] of SCALAR_CONSTS) {
  const value = contract[field];
  if (typeof value !== "string") {
    console.error(
      `gen-python: contract field '${field}' is missing or not a string (got ${JSON.stringify(value)}); ` +
      `cannot derive Python const ${toUpperSnake(name)}. The contract instance must validate against the schema first.`
    );
    process.exit(1);
  }
  derived.push({ pyName: toUpperSnake(name), field, doc, value });
}

// --- escape a derived value for safe embedding in a Python string literal -----
function pyStringLiteral(s) {
  // JSON double-quoted escapes are a subset of Python's; the resulting literal
  // is valid Python with identical runtime value for these contract strings.
  return JSON.stringify(s);
}

// --- emit -------------------------------------------------------------------
const lines = [];
lines.push("# Code generated by tools/gen-python — DO NOT EDIT.");
lines.push("#");
lines.push("# Source of truth: mcp/mcp-plugin-delivery.contract.json (validated against");
lines.push("# mcp/mcp-plugin-delivery.schema.json). Every value below is DERIVED from that");
lines.push("# contract instance, never hand-written. Regenerate with:");
lines.push("#");
lines.push("#     node tools/gen-python.mjs");
lines.push("#");
lines.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
lines.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
lines.push("");
lines.push("# Derived scalar string constants from the MCP plugin-delivery contract.");
lines.push("");
const exported = [];
for (const { pyName, field, doc, value } of derived) {
  lines.push(`# ${pyName} is derived from contract field "${field}": ${doc}`);
  lines.push(`${pyName} = ${pyStringLiteral(value)}`);
  lines.push("");
  exported.push(pyName);
}
lines.push("__all__ = [");
for (const name of exported) {
  lines.push(`    ${pyStringLiteral(name)},`);
}
lines.push("]");
lines.push("");

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-python: wrote ${OUT_PATH} (${derived.length} consts derived from ${CONTRACT_PATH})`);
