#!/usr/bin/env node
// gen-python.mjs — generate Python bindings from the MCP plugin-delivery contract IDL.
//
// Why Node (.mjs) and not Python? For consistency and zero added toolchain: all
// three generators (Go, TS, Python) are Node scripts, so the drift gate needs
// only `node` — no Python interpreter in CI. Generating Python *source* from
// Node is fine; the emitted module is plain idiomatic Python.
//
// IMPORTANT (the whole point of this generator):
//   Every emitted constant VALUE is DERIVED from the contract JSON instance at
//   `mcp/mcp-plugin-delivery.contract.json`. NOTHING is hardcoded here — there is
//   deliberately no string literal "provision_workspace" (or any other contract
//   value) anywhere in this file. Rename the verb in the contract and re-run, and
//   the generated `REQUIRED_TOOL` changes with it. That is what makes the schema
//   `const` pin + the validate CI + the drift gate load-bearing end to end.
//
// Usage:
//   node tools/gen-python.mjs            # write gen/python/contract_gen.py
//   node tools/gen-python.mjs --check    # print to stdout, do not write (debug)
//
// Run from the repo root (paths below are resolved relative to this file's
// location, so cwd does not matter).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildCommsModelIR, buildModelIR, upperSnake } from "./lib/comms-schema.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const CONTRACT_PATH = resolve(repoRoot, "mcp/mcp-plugin-delivery.contract.json");
const OUT_PATH = resolve(repoRoot, "gen/python/contract_gen.py");
const COMMS_OUT_PATH = resolve(repoRoot, "gen/python/workspace_comms_gen.py");

// --- read the canonical IDL instance ----------------------------------------
const raw = readFileSync(CONTRACT_PATH, "utf8");
let contract;
try {
  contract = JSON.parse(raw);
} catch (err) {
  console.error(`gen-python: ${CONTRACT_PATH} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// --- derive the scalar string constants we expose ----------------------------
// Each entry maps a logical const identifier to the contract field it is DERIVED
// from. This is the SAME scalar set the Go and TS generators emit; keep the
// three in lockstep. Python idiom = module-level UPPER_SNAKE_CASE constants, so
// we carry the canonical PascalCase identifier and convert it deterministically
// below. The nested `runtimes` / `port` objects are intentionally NOT modeled
// here in this first pass (see tools/README.md "Follow-ons").
const SCALAR_CONSTS = [
  // Canonical name          contract field             doc
  ["RequiredTool", "required_tool",
    "the singular tool verb the concierge management MCP must expose; the degrade gate fails closed if it is absent on the live surface (the #3082 phantom-verb invariant)."],
  ["MCPServerName", "mcp_server_name",
    "logical name of the management-mode MCP server descriptor."],
  ["SettingsKey", "key",
    "top-level key inside the settings file under which MCP servers are declared."],
  ["DefaultSettingsPath", "settings_path",
    "default (claude_code) settings file path the rendered MCP descriptor is written to."],
  ["LoadedMCPToolsField", "loaded_mcp_tools_field",
    "name of the field reporting the set of tools actually loaded from the MCP server."],
  ["RuntimePresentField", "runtime_present_field",
    "name of the runtime-reported boolean field indicating the MCP server is present."],
  ["LegacyBinaryPath", "legacy_binary_path",
    "filesystem path of the legacy MCP server binary older presence probes checked."],
];

// PascalCase -> UPPER_SNAKE_CASE (idiomatic Python module constant), with runs
// of capitals (e.g. "MCP") kept together: MCPServerName -> MCP_SERVER_NAME.
function toUpperSnake(pascal) {
  return pascal
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

const derived = [];
for (const [name, field, doc] of SCALAR_CONSTS) {
  const value = contract[field];
  if (typeof value !== "string") {
    console.error(
      `gen-python: contract field '${field}' is missing or not a string (got ${JSON.stringify(value)}); ` +
      `cannot derive Python const ${toUpperSnake(name)}. The contract instance must validate against the schema first.`
    );
    process.exit(1);
  }
  derived.push({ pyName: toUpperSnake(name), field, doc, value });
}

// --- escape a derived value for safe embedding in a Python string literal -----
function pyStringLiteral(s) {
  // JSON double-quoted escapes are a subset of Python's; the resulting literal
  // is valid Python with identical runtime value for these contract strings.
  return JSON.stringify(s);
}

// --- emit -------------------------------------------------------------------
const lines = [];
lines.push("# Code generated by tools/gen-python — DO NOT EDIT.");
lines.push("#");
lines.push("# Source of truth: mcp/mcp-plugin-delivery.contract.json (validated against");
lines.push("# mcp/mcp-plugin-delivery.schema.json). Every value below is DERIVED from that");
lines.push("# contract instance, never hand-written. Regenerate with:");
lines.push("#");
lines.push("#     node tools/gen-python.mjs");
lines.push("#");
lines.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
lines.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
lines.push("");
lines.push("# Derived scalar string constants from the MCP plugin-delivery contract.");
lines.push("");
const exported = [];
for (const { pyName, field, doc, value } of derived) {
  lines.push(`# ${pyName} is derived from contract field "${field}": ${doc}`);
  lines.push(`${pyName} = ${pyStringLiteral(value)}`);
  lines.push("");
  exported.push(pyName);
}
lines.push("__all__ = [");
for (const name of exported) {
  lines.push(`    ${pyStringLiteral(name)},`);
}
lines.push("]");
lines.push("");

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-python: wrote ${OUT_PATH} (${derived.length} consts derived from ${CONTRACT_PATH})`);

// ===========================================================================
// workspace-comms models (Wave 2). Derived from workspace-comms/*.schema.json
// via the shared IR (tools/lib/comms-schema.mjs). The mcp output above is left
// BYTE-IDENTICAL — this is a strictly-additional second module. This is the
// highest-value artifact: ONE importable set of TypedDicts that both
// molecule-ai-sdk and molecule_runtime can share so their comms payloads cannot
// drift. Class/field names are STRUCTURAL (schema shape); the only string VALUES
// written are the `const`-pinned literals, derived from the schema.
// ===========================================================================

const PY_SCALAR = { string: "str", int: "int", float: "float", bool: "bool", any: "Any" };

function pyType(ref) {
  switch (ref.k) {
    case "scalar": return PY_SCALAR[ref.t];
    case "named": return ref.name;
    case "array": return `List[${pyType(ref.items)}]`;
    case "map": return `Dict[str, ${pyType(ref.value)}]`;
    default: throw new Error(`gen-python: unknown TypeRef kind ${ref.k}`);
  }
}

const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;

const commsIR = buildCommsModelIR(repoRoot);

const P = [];
P.push("# Code generated by tools/gen-python — DO NOT EDIT.");
P.push("#");
P.push("# Source of truth: workspace-comms/*.schema.json (each validated against its");
P.push("# sibling *.contract.json instance by .gitea/workflows/validate-contracts.yml).");
P.push("# Every class, field and constant below is DERIVED from those schemas, never");
P.push("# hand-written. Regenerate with:");
P.push("#");
P.push("#     node tools/gen-python.mjs");
P.push("#");
P.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
P.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
P.push("");
P.push("from __future__ import annotations");
P.push("");
P.push("from typing import Any, Dict, List, TypedDict");
P.push("");
P.push("try:  # NotRequired is stdlib on Python 3.11+");
P.push("    from typing import NotRequired");
P.push("except ImportError:  # pragma: no cover - Python < 3.11");
P.push("    from typing_extensions import NotRequired");
P.push("");

const commsExported = [];

if (commsIR.consts.length) {
  P.push("# Load-bearing string literals pinned by `const` in the workspace-comms schemas.");
  P.push("");
  for (const c of commsIR.consts) {
    const name = upperSnake(c.name);
    P.push(`# ${name} is pinned by ${c.source}: ${c.doc}`);
    P.push(`${name} = ${pyStringLiteral(c.value)}`);
    P.push("");
    exported.push(name);
  }
}

for (const def of commsIR.types) {
  P.push(`class ${def.name}(TypedDict):`);
  const docLines = [];
  if (def.doc) docLines.push(`    """${def.doc}"""`);
  if (def.fields.length === 0) {
    if (docLines.length) P.push(...docLines);
    else P.push("    pass");
    P.push("");
    exported.push(def.name);
    continue;
  }
  if (docLines.length) {
    P.push(...docLines);
    P.push("");
  }
  for (const field of def.fields) {
    if (!IDENT.test(field.key)) {
      console.error(`gen-python: field key '${field.key}' in ${def.name} is not a valid Python identifier; class-syntax TypedDict cannot express it.`);
      process.exit(1);
    }
    if (field.doc) P.push(`    # ${field.doc}`);
    const ty = pyType(field.type);
    P.push(`    ${field.key}: ${field.required ? ty : `NotRequired[${ty}]`}`);
  }
  P.push("");
  exported.push(def.name);
}

P.push("__all__ = [");
for (const name of exported) {
  P.push(`    ${pyStringLiteral(name)},`);
}
P.push("]");
P.push("");

const commsOut = P.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(COMMS_OUT_PATH), { recursive: true });
  writeFileSync(COMMS_OUT_PATH, commsOut, "utf8");
  console.error(`gen-python: wrote ${COMMS_OUT_PATH} (${commsIR.types.length} TypedDicts + ${commsIR.consts.length} consts derived from workspace-comms/*.schema.json)`);
}

// ===========================================================================
// marketplace catalog contract models (Wave 3). Derived from the three artifact
// manifests + the unified catalog-entry envelope via the SAME shared IR walker
// (buildModelIR over the catalog surface dirs). The mcp + workspace-comms output
// above is left BYTE-IDENTICAL — this is a strictly-additional third module: ONE
// importable set of TypedDicts a marketplace/CP consumer can share. Class/field
// names are STRUCTURAL (schema shape). The per-kind catalog `spec` is a oneOf
// keyed on `kind`; codegen models the discriminated spec TypedDicts and the
// envelope's open `spec` field as Dict[str, Any].
// ===========================================================================

const CATALOG_DIRS = ["plugin-manifest", "workspace-template", "org-template", "catalog"];
const CATALOG_OUT_PATH = resolve(repoRoot, "gen/python/catalog_gen.py");
const catalogIR = buildModelIR(repoRoot, CATALOG_DIRS);

const PC = [];
PC.push("# Code generated by tools/gen-python — DO NOT EDIT.");
PC.push("#");
PC.push("# Source of truth: the marketplace catalog contract schemas");
PC.push("# (plugin-manifest/, workspace-template/, org-template/, catalog/ — each");
PC.push("# validated against its sibling *.contract.json instance by");
PC.push("# .gitea/workflows/validate-contracts.yml). Every class, field and constant");
PC.push("# below is DERIVED from those schemas, never hand-written. Regenerate with:");
PC.push("#");
PC.push("#     node tools/gen-python.mjs");
PC.push("#");
PC.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
PC.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
PC.push("");
PC.push("from __future__ import annotations");
PC.push("");
PC.push("from typing import Any, Dict, List, TypedDict");
PC.push("");
PC.push("try:  # NotRequired is stdlib on Python 3.11+");
PC.push("    from typing import NotRequired");
PC.push("except ImportError:  # pragma: no cover - Python < 3.11");
PC.push("    from typing_extensions import NotRequired");
PC.push("");

const catalogExported = [];

if (catalogIR.consts.length) {
  PC.push("# Load-bearing string literals pinned by `const` in the catalog contract schemas.");
  PC.push("");
  for (const c of catalogIR.consts) {
    const name = upperSnake(c.name);
    PC.push(`# ${name} is pinned by ${c.source}: ${c.doc}`);
    PC.push(`${name} = ${pyStringLiteral(c.value)}`);
    PC.push("");
    catalogExported.push(name);
  }
}

for (const def of catalogIR.types) {
  PC.push(`class ${def.name}(TypedDict):`);
  const docLines = [];
  if (def.doc) docLines.push(`    """${def.doc}"""`);
  if (def.fields.length === 0) {
    if (docLines.length) PC.push(...docLines);
    else PC.push("    pass");
    PC.push("");
    catalogExported.push(def.name);
    continue;
  }
  if (docLines.length) {
    PC.push(...docLines);
    PC.push("");
  }
  for (const field of def.fields) {
    if (!IDENT.test(field.key)) {
      console.error(`gen-python: field key '${field.key}' in ${def.name} is not a valid Python identifier; class-syntax TypedDict cannot express it.`);
      process.exit(1);
    }
    if (field.doc) PC.push(`    # ${field.doc}`);
    const ty = pyType(field.type);
    PC.push(`    ${field.key}: ${field.required ? ty : `NotRequired[${ty}]`}`);
  }
  PC.push("");
  catalogExported.push(def.name);
}

PC.push("__all__ = [");
for (const name of catalogExported) {
  PC.push(`    ${pyStringLiteral(name)},`);
}
PC.push("]");
PC.push("");

const catalogOut = PC.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(CATALOG_OUT_PATH), { recursive: true });
  writeFileSync(CATALOG_OUT_PATH, catalogOut, "utf8");
  console.error(`gen-python: wrote ${CATALOG_OUT_PATH} (${catalogIR.types.length} TypedDicts + ${catalogIR.consts.length} consts derived from the catalog contract schemas)`);
}
